trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pre-commit
    pre-commit install-hooks
  displayName: 'Install Python dependencies'

- task: UseGoVersion@0
  inputs:
    version: '1.16'
    addToPath: true

- script: |
    go get -u github.com/gruntwork-io/terratest/modules/terraform
    go get -u github.com/stretchr/testify/assert
  displayName: 'Install Go dependencies'

- script: pre-commit run --all-files
  displayName: 'Run pre-commit'

- script: go test -v ./test
  displayName: 'Run Terratest'

- script: terraform-compliance -f compliance
  displayName: 'Run Terraform Compliance'
